start referee configs
Ararabots-UFMS/vsss24-ws pull request #113
Opened 2024-09-11 20:12 UTC by fernandoGonc12

2024-09-25 21:50 UTC, FabioHuang requested changes

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_client.py
> +            data, _ = self.sock.recvfrom(2048)
Why wait a bigger size message? dont think there is a 2x buffer size message begin sent

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/publisher_referee.py
> +        self.publisher_ = self.create_publisher(String, 'topic', 10)
This is sending a String message, instead, it needs to be a custom message format in System Interfaces module to process game controller protobufs

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_node.py
> +BUFFER_SIZE = 1024
Dont use constants in the node file. change it so that those constants can be used as a parameter in the node

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_node.py
> +    sys.exit(1)
Why handle imports errors here? inst it expected to be able to import it

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_node.py
> +class MulticastListener(Node):
Inst this name too general? It is only a referee subscriber, not a general multicast subscriber

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_node.py
> +        # Configuração do socket multicast
There is a client class doing the socket configuration, but not being used here.

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_node.py
> +        while rclpy.ok():
Use a ros2 timer instead of the while loop

2024-09-25 21:50 UTC, FabioHuang commented on src/referee/referee/referee_subscriber.py
> +        # Aqui você pode adicionar qualquer processamento adicional ou lógica de salvamento
The message needs to be process then send, not processed in the end user

2024-10-08 22:13 UTC, Marcelo-Filho112 commented
Just look at these packages: referee, control_unit, utils and system interface.

2024-10-09 23:27 UTC, guilherme-teles-dev commented on README.md
Se a gente ta fazendo a documentação para os proximos membros do Arara, compensa colocar a documentação em inglês?

2024-10-16 15:07 UTC, merged